// <auto-generated />
using System;
using BoardGameLibrary.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameLibrary.Api.Migrations
{
    [DbContext(typeof(BoardGameDbContext))]
    [Migration("20260926210000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BoardGameLibrary.Api.Models.BoardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BggId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BggAverageRating")
                        .HasPrecision(4, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("BggBestWith")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BggUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPlayTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BggId")
                        .IsUnique();

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("BoardGameLibrary.Api.Models.PlayerCountRating", b =>
                {
                    b.Property<int>("BoardGameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.HasKey("BoardGameId", "PlayerCount");

                    b.HasIndex("PlayerCount");

                    b.ToTable("PlayerCountRatings");
                });

            modelBuilder.Entity("BoardGameLibrary.Api.Models.PlayerCountRating", b =>
                {
                    b.HasOne("BoardGameLibrary.Api.Models.BoardGame", "BoardGame")
                        .WithMany("PlayerCountRatings")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("BoardGameLibrary.Api.Models.BoardGame", b =>
                {
                    b.Navigation("PlayerCountRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
