// <auto-generated />
using BoardGameLibrary.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameLibrary.Api.Migrations
{
    [DbContext(typeof(BoardGameDbContext))]
    [Migration("20260926155458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BoardGameLibrary.Api.Models.BoardGame", b =>
                {
                    b.Property<int>("BggId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BggAverageRating")
                        .HasColumnType("REAL");

                    b.Property<int?>("BggRatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BggId");

                    b.ToTable("BoardGames");
                });

            modelBuilder.Entity("BoardGameLibrary.Api.Models.PlayerCountRecommendation", b =>
                {
                    b.Property<int>("BoardGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerCount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BestVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotRecommendedVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecommendedVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardGameId", "PlayerCount");

                    b.ToTable("PlayerCountRecommendations");
                });

            modelBuilder.Entity("BoardGameLibrary.Api.Models.PlayerCountRecommendation", b =>
                {
                    b.HasOne("BoardGameLibrary.Api.Models.BoardGame", "BoardGame")
                        .WithMany("PlayerCountRecommendations")
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");
                });

            modelBuilder.Entity("BoardGameLibrary.Api.Models.BoardGame", b =>
                {
                    b.Navigation("PlayerCountRecommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
